#!/usr/bin/env bash
# A bash while loop to print a text ten times with an exception on the 9th iteration

i=1
while [ $i -le 10 ]
do
	if [[ "$i" == '9' ]]; then
		echo -e "Best School\nHi"
	fi
	echo Best School
	((i++))
done
