#!/usr/bin/env bash
# A bash while loop to print a text ten times with an exception on the 9th iteration

i=1
while [ $i -lt 10 ]
do
  if [ $i -eq 9 ]
  then
    echo "Hi"
  fi
  echo "Best School"
  (( i++ ))
done
