#!/usr/bin/env bash
# A bash while loop to display differnt texts depending on the conditions stated for the iterations

i=1
while [ $i -le 10 ]
do
	if [[ "$i" == '4' ]]; then
	  echo bad luck
	elif [[ "$i" == '8' ]]; then
	  echo good luck
	else
	  echo Best School
	fi
	((i++))
done
