#!/usr/bin/env bash
# A bash while loop to iterate through 1 to 20 and diplay texts depending on the conditions

i=1
while [ $i -le 20 ]
do
	case $i in

	  4)
	    echo -e "$i\nbad luck from China"
	    ;;

          9)
	    echo -e "$i\nbad luck from Japan"
	    ;;

	  17)
	    echo -e "$i\nbad luck from Italy"
	    ;;

	  *)
	    echo -e "$i"
	    ;;
	esac

	((i++))
done
